### ISSUE TITLE
Importmap completion?

### ISSUE THREAD

**Issue by mightysun99** [alejandroliu/pocketmine-plugins#1]
Is import map able to be used yet?

**Comment by alejandroliu** [comment]
Right now I consider it a proof-of-concept.  It can take PC maps and convert them so they can be played on Pocket Edition (without the client crashing).  I am able to explore a few maps that way.  However the following things would happen:
1. Chunks are sometimes corrupted.
2. Entities and Tiles are not converted/copied.

Also, since PocketMine does not have the same Generations and MineCraft, dynamically generated terrain does not match the rest of the scenery.

**Comment by alejandroliu** [comment]
The latest (v2.0.0) should work fine.  I don't use the ImportMap plugin, since using `pmimporter` directly is much convenient.
