### ISSUE TITLE
Floats not spawning in ALL worlds

### ISSUE THREAD

**Issue by autonomousperson** [alejandroliu/pocketmine-plugins#18]
When server is running, player only sees floating sign in the spawn world. When they join a different world, they do not see the sign there. The reload command (/reload not /ls reload) needs to be ran for the signs to come back.

Proposed fix?
Re spawn signs on player tp?
Add a auto sign respawn time in config?

Server is minepocket.com pm Autonomousperson for a demo of the bug.

**Comment by alejandroliu** [comment]
I can't find your server.

Also, I am unable to recreate what you describe here.  LiveSigns supports multiworld, so if I create a sign in spawn world, it only appears in spawn world.  If I join a different world, I should _not_ see the sign there.  If I would like to see that sign there, then I need to recreate it.   Because all signs refer to the same ids, the same content is only loaded once.

Also, doing a /reload does not make the sign appear in the different world.

**Comment by PEMapModder** [comment]
pm?
