### ISSUE TITLE
Chunks

### ISSUE THREAD

**Issue by astersx** [alejandroliu/pocketmine-plugins#22]
Hi , i wanna know , why it show chunks from the main map ? In new map it show the spawn from the main map ... Is there a way to fix it ?

**Comment by alejandroliu** [comment]
I don't understand this.

**Comment by astersx** [comment]
wow , i create new world named "pvp" . Now i have worlds "world" , "pvp" ... Building spawn of "world" is in "pvp"  , Understand?

**Comment by alejandroliu** [comment]
There are 20 different plugins in this repository.  I have no idea what plugin you want to address, what is the issue that you are having, what results do you see, what results were you expecting to see.

**Comment by AndreyNazarchuk** [comment]
ManyWorlds.

**Comment by alejandroliu** [comment]
So, that is not a ManyWorlds issue.  It is a PocketMine / MCPE client server issue.

Essentially when you teleport, it takes some time for the chunks to be sent.  The same happens when you connect to the server for the first time, you will get a screen saying "Building terrain", which this may take more or less time. The difference is when you teleport is that you actually see the chunks being loaded (instead of getting a "building terrain" screen).

One possible way to handle is to do teleports via Fast Transfer, but I wouldn't implement this in ManyWorlds.

**Comment by astersx** [comment]
Ok thx , so fast transfer will fix this . I saw other servers with more than 1 world and there was no problems.
